version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=dev
    networks:
      - backend
  app:
    container_name: youtube-api
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env.dev
    ports:
      - 3000:3000
    links: 
      - mongo  
    depends_on:
      - mongo  
    networks:
      - backend

networks:
  backend:
    driver: bridge    
